// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About/About.vue')['default']
    Backdrop: typeof import('./components/Dropdown/Backdrop.vue')['default']
    Card: typeof import('./components/About/Card.vue')['default']
    Cards: typeof import('./components/About/Cards.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Description: typeof import('./components/About/Description.vue')['default']
    Descriptions: typeof import('./components/About/Descriptions.vue')['default']
    Dropdown: typeof import('./components/Dropdown/Dropdown.vue')['default']
    ErrorList: typeof import('./components/Visit/ErrorList.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    LandingPage: typeof import('./components/LandingPage/LandingPage.vue')['default']
    LanguageDropdown: typeof import('./components/Navbar/LanguageDropdown.vue')['default']
    Map: typeof import('./components/Map/Map.vue')['default']
    Navbar: typeof import('./components/Navbar/Navbar.vue')['default']
    Post: typeof import('./components/Blog/post.vue')['default']
    PricingPlan: typeof import('./components/About/PricingPlan.vue')['default']
    PricingPlans: typeof import('./components/About/PricingPlans.vue')['default']
    README: typeof import('./components/README.md')['default']
    Recipe: typeof import('./components/About/Recipe.vue')['default']
    Recipes: typeof import('./components/About/Recipes.vue')['default']
    Testimonial: typeof import('./components/About/Testimonial.vue')['default']
    Testimonials: typeof import('./components/About/Testimonials.vue')['default']
    VisitCalendar: typeof import('./components/VisitCalendar/VisitCalendar.vue')['default']
    VisitInput: typeof import('./components/Visit/visitInput.vue')['default']
  }
}

export { }
